# Generated by Django 5.1.1 on 2024-10-10 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=10, verbose_name='Dia')),
            ],
            options={
                'verbose_name': 'Dia',
                'verbose_name_plural': 'Dias',
                'db_table': 'Dias',
            },
        ),
        migrations.CreateModel(
            name='HorarioDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=10, verbose_name='Horario')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'Horarios',
            },
        ),
        migrations.CreateModel(
            name='ReferenteDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('dni', models.IntegerField(verbose_name='Dni')),
            ],
            options={
                'verbose_name': 'Referente',
                'verbose_name_plural': 'Referentes',
                'db_table': 'Referentes',
            },
        ),
        migrations.CreateModel(
            name='EspacioDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('coordenadas', models.CharField(max_length=100, verbose_name='Coordenadas')),
                ('barrio', models.CharField(max_length=100, verbose_name='Barrio')),
                ('tarjeta', models.BooleanField(verbose_name='Tarjeta')),
                ('asistencia', models.IntegerField(verbose_name='Asistencia')),
                ('dia', models.ManyToManyField(to='EspaciosComunitarios.diadb', verbose_name='Dia')),
                ('horario', models.ManyToManyField(to='EspaciosComunitarios.horariodb', verbose_name='Horario')),
                ('referente_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EspaciosComunitarios.referentedb')),
            ],
            options={
                'verbose_name': 'Espacio comunitario',
                'verbose_name_plural': 'Espacios comunitarios',
                'db_table': 'Espacios comunitarios',
            },
        ),
        migrations.CreateModel(
            name='RetiroDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripcion')),
                ('agente', models.CharField(max_length=100, verbose_name='Agente')),
                ('espacio_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiros', to='EspaciosComunitarios.espaciodb')),
            ],
            options={
                'verbose_name': 'Retiro',
                'verbose_name_plural': 'Retiros',
                'db_table': 'Retiros',
            },
        ),
    ]
